<?php

namespace Database\Seeders;

use App\Models\DealerProfile;
use Illuminate\Database\Seeder;

class DealerProfileSeeder extends Seeder
{
    public function run(): void
    {
        $dealers = [
            [
                'dealer_code' => 'DEFAULT',
                'dealer_name' => '기본 대리점',
                'contact_person' => '관리자',
                'phone' => '02-1234-5678',
                'address' => '서울시 강남구',
                'default_sim_fee' => 0,
                'default_mnp_discount' => 800,
                'tax_rate' => 0.10,
                'default_payback_rate' => 0.00,
                'status' => 'active',
                'activated_at' => now(),
            ],
            [
                'dealer_code' => 'ENT',
                'dealer_name' => '이앤티',
                'contact_person' => '김대리',
                'phone' => '02-2222-3333',
                'address' => '서울시 서초구',
                'default_sim_fee' => 0,
                'default_mnp_discount' => 800,
                'tax_rate' => 0.10,
                'default_payback_rate' => 2.50,
                'status' => 'active',
                'activated_at' => now(),
            ],
            [
                'dealer_code' => 'WIN',
                'dealer_name' => '앤투윈',
                'contact_person' => '박과장',
                'phone' => '02-3333-4444',
                'address' => '서울시 종로구',
                'default_sim_fee' => 0,
                'default_mnp_discount' => 800,
                'tax_rate' => 0.10,
                'default_payback_rate' => 1.80,
                'status' => 'active',
                'activated_at' => now(),
            ],
            [
                'dealer_code' => 'CHOSI',
                'dealer_name' => '초시대',
                'contact_person' => '이팀장',
                'phone' => '02-4444-5555',
                'address' => '부산시 해운대구',
                'default_sim_fee' => 0,
                'default_mnp_discount' => 800,
                'tax_rate' => 0.10,
                'default_payback_rate' => 3.00,
                'status' => 'active',
                'activated_at' => now(),
            ],
            [
                'dealer_code' => 'SM',
                'dealer_name' => 'SM',
                'contact_person' => 'SM 담당자',
                'phone' => '02-1111-2222',
                'address' => '서울시 중구',
                'default_sim_fee' => 0,
                'default_mnp_discount' => 800,
                'tax_rate' => 0.10,
                'default_payback_rate' => 2.00,
                'status' => 'active',
                'activated_at' => now(),
            ],
            [
                'dealer_code' => 'W',
                'dealer_name' => 'W',
                'contact_person' => 'W 담당자',
                'phone' => '02-2222-3333',
                'address' => '서울시 강남구',
                'default_sim_fee' => 0,
                'default_mnp_discount' => 800,
                'tax_rate' => 0.10,
                'default_payback_rate' => 1.80,
                'status' => 'active',
                'activated_at' => now(),
            ],
            [
                'dealer_code' => 'KING',
                'dealer_name' => '더킹',
                'contact_person' => '더킹 담당자',
                'phone' => '02-3333-4444',
                'address' => '서울시 서초구',
                'default_sim_fee' => 0,
                'default_mnp_discount' => 800,
                'tax_rate' => 0.10,
                'default_payback_rate' => 2.50,
                'status' => 'active',
                'activated_at' => now(),
            ],
            [
                'dealer_code' => 'ENTER',
                'dealer_name' => '엔터',
                'contact_person' => '엔터 담당자',
                'phone' => '02-4444-5555',
                'address' => '서울시 마포구',
                'default_sim_fee' => 0,
                'default_mnp_discount' => 800,
                'tax_rate' => 0.10,
                'default_payback_rate' => 2.20,
                'status' => 'active',
                'activated_at' => now(),
            ],
            [
                'dealer_code' => 'UP',
                'dealer_name' => '유피',
                'contact_person' => '유피 담당자',
                'phone' => '02-5555-6666',
                'address' => '서울시 용산구',
                'default_sim_fee' => 0,
                'default_mnp_discount' => 800,
                'tax_rate' => 0.10,
                'default_payback_rate' => 1.90,
                'status' => 'active',
                'activated_at' => now(),
            ],
            [
                'dealer_code' => 'TAESUNG',
                'dealer_name' => '태성',
                'contact_person' => '태성 담당자',
                'phone' => '02-6666-7777',
                'address' => '서울시 송파구',
                'default_sim_fee' => 0,
                'default_mnp_discount' => 800,
                'tax_rate' => 0.10,
                'default_payback_rate' => 2.30,
                'status' => 'active',
                'activated_at' => now(),
            ],
            [
                'dealer_code' => 'PDM',
                'dealer_name' => '피디엠',
                'contact_person' => '피디엠 담당자',
                'phone' => '02-7777-8888',
                'address' => '서울시 영등포구',
                'default_sim_fee' => 0,
                'default_mnp_discount' => 800,
                'tax_rate' => 0.10,
                'default_payback_rate' => 2.10,
                'status' => 'active',
                'activated_at' => now(),
            ],
            [
                'dealer_code' => 'HANJU',
                'dealer_name' => '한주',
                'contact_person' => '한주 담당자',
                'phone' => '02-8888-9999',
                'address' => '경기도 안양시',
                'default_sim_fee' => 0,
                'default_mnp_discount' => 800,
                'tax_rate' => 0.10,
                'default_payback_rate' => 1.95,
                'status' => 'active',
                'activated_at' => now(),
            ],
            [
                'dealer_code' => 'HAPPY',
                'dealer_name' => '해피',
                'contact_person' => '해피 담당자',
                'phone' => '02-9999-0000',
                'address' => '인천시 부평구',
                'default_sim_fee' => 0,
                'default_mnp_discount' => 800,
                'tax_rate' => 0.10,
                'default_payback_rate' => 2.40,
                'status' => 'active',
                'activated_at' => now(),
            ],
        ];

        foreach ($dealers as $dealer) {
            DealerProfile::firstOrCreate(
                ['dealer_code' => $dealer['dealer_code']],
                $dealer
            );
        }

        echo 'DealerProfile 시더 실행 완료: '.count($dealers)."개 대리점 생성\n";
    }
}
