[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile.simple"

[deploy]
healthcheckPath = "/health.php"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
internalPort = 8080
# Start command is handled by Dockerfile ENTRYPOINT
