[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile"

[deploy]
healthcheckPath = "/health.php"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
# Start command is handled by Dockerfile CMD
