[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile.apache"

[deploy]
healthcheckPath = "/health.txt"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
internalPort = 8080
# Start command is handled by Dockerfile ENTRYPOINT
